version: '3.6'

services:

  intelliq-app:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: intelliq-app:${ISOLATION_ID}
    container_name: intelliq-app
    volumes:
      - ../intelliq:/go/src/github.com/intelliq
        #      - ./:/go/src/github.com/intelliq/app
      - ./keys:/var/lib/intelliq/.ssh
    depends_on:
      - mongo-db
      - redis
    expose:
      - 8080
    ports:
      - 8080:8080

  mongo-db:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    image: mongo-db:${ISOLATION_ID}
    container_name: mongo-db
    restart: always
    expose:
      - 27017

  redis:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-redis
    image: redis:${ISOLATION_ID}
    container_name: redis
    expose:
      - 6379

  angular-app:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: angular-app:${ISOLATION_ID}
    container_name: angular-app
    volumes:
      - ./keys:/var/lib/intelliq/.ssh
    depends_on:
      - intelliq-app
    ports:
      - "4200:4200"
  
