FROM ubuntu:bionic

RUN apt-get update \
 && apt-get install gnupg -y


RUN apt-get install -y -q \
    curl \
    wget \
    tar \
    make \
    g++ \
    apt-transport-https \
    ca-certificates \
    software-properties-common

# Install Redis.
RUN \
  cd /tmp && \
  wget http://download.redis.io/redis-stable.tar.gz && \
  tar xvzf redis-stable.tar.gz && \
  cd redis-stable && \
  make && \
  make install && \
  cp -f src/redis-sentinel /usr/local/bin && \
  mkdir -p /etc/redis && \
  cp -f *.conf /etc/redis && \
  rm -rf /tmp/redis-stable* && \
  sed -i 's/^\(daemonize .*\)$/# \1/' /etc/redis/redis.conf && \
  sed -i 's/^\(dir .*\)$/# \1\ndir \/data/' /etc/redis/redis.conf && \
  sed -i 's/^\(logfile .*\)$/# \1/' /etc/redis/redis.conf && \
  sed -i "/bind 127.0.0.1/c bind 0.0.0.0" /etc/redis/redis.conf && \
  sed -i "/protected-mode yes/c protected-mode no" /etc/redis/redis.conf

# Define mountable directories.
VOLUME ["/data"]

# Define working directory.
WORKDIR /data

RUN sysctl vm.overcommit_memory=1

RUN sysctl -w net.core.somaxconn=1024

# Define default command.
CMD ["redis-server", "/etc/redis/redis.conf"]

# Expose ports.
EXPOSE 6379
